#ifndef FEEDER_BIRD_ART_H
#define FEEDER_BIRD_ART_H
// Generated by tools/sheet_cut.py --bake - do not edit.
// Straight (not premultiplied) RGBA, profile facing left; the engine mirrors.
#include "fish_art.h"

struct BirdSprite {
  const char*  name;     // species_pose, as in sprites.json
  uint8_t      w, h;
  float        ax, ay;   // anchor: feet on a perch, body centre in flight
  const RGBA8* px;
};

static const int N_BIRD_SPRITES = 56;
extern const BirdSprite BIRD_SPRITES[N_BIRD_SPRITES];
const BirdSprite* birdSprite(const char* name);   // nullptr if there is none

#endif // FEEDER_BIRD_ART_H
