#ifndef FEEDER_ART_H
#define FEEDER_ART_H
// Generated by tools/make_assets.py - do not edit.
#include "fish_art.h"

enum SpotKind : uint8_t { SPOT_PERCH, SPOT_TRAY, SPOT_SIDE, SPOT_BRANCH, SPOT_TRUNK, SPOT_GROUND };

struct FeederSpot {
  const char* name;
  SpotKind    kind;
  bool        onFeeder;  // true: x, y from the pivot, swinging; false: scene pixels
  float       x, y;
  float       x1, y1;    // the far corner, for an area (the ground)
  float       scale;     // how big a bird is drawn here, from the depth map
};

static const int FEEDER_W = 116;
static const int FEEDER_H = 99;
static const float FEEDER_PIVOT_X = 171.82f;   // scene pixels
static const float FEEDER_PIVOT_Y = 80.00f;
static const float FEEDER_ANCHOR_X = 58.82f;  // the pivot inside the sprite
static const float FEEDER_ANCHOR_Y = 0.00f;
static const float PX_PER_CM = 2.4f;
// the feeder as it looks in each background (FEEDER_BG order), 11484 pixels each
extern const RGBA8* const FEEDER_ARTS[3];
// only the roof and the front post: drawn again over the birds on the tray
extern const RGBA8* const FEEDER_FRONTS[3];

static const int N_FEEDER_SPOTS = 13;
extern const FeederSpot FEEDER_SPOTS[N_FEEDER_SPOTS];
// bird size on the ground, per scene row, from the depth map
extern const float GROUND_SCALE[240];
// the branch in the photo, 0..255 per scene pixel (y * 320 + x): where the sway bends it
extern const uint8_t BRANCH_MASK[76800];
// the wood alone, not widened: it hides the leaves and flakes falling behind it
extern const uint8_t BRANCH_WOOD[76800];

#endif
