#ifndef FEEDER_BG_H
#define FEEDER_BG_H
// Generated by tools/make_assets.py - do not edit.
#include <Arduino.h>

struct FeederBg { const uint8_t* data; uint32_t len; };

static const int N_FEEDER_BG = 3;
static const int BG_WINTER_OVERCAST = 0;
static const int BG_WINTER_MORNING = 1;
static const int BG_AUTUMN = 2;
extern const FeederBg FEEDER_BG[N_FEEDER_BG];

#endif
