"""Bakes the feeder scene's pictures into main/scene.

    python tools/make_assets.py art [--overlay out.png]

  feeder_bg.cpp   the three backgrounds without the feeder (bg_*_empty.png),
                  resized to the engine's 320x240 and re-encoded as JPEG q90
  feeder_art.cpp  the feeder alone, once per background: its outline is
                  feeder_cutout.png's alpha inside feeder_mask.png, its colours
                  come from that background's own photo with the feeder (bg_*.png;
                  snow on the roof in winter, wet wood in autumn - the three
                  photos differ from their empty versions only inside the feeder),
                  cut below the knot (the branch and the knot stay in the
                  background, only what hangs swings), reduced to scene pixels
                  with a premultiplied box filter; with its pivot,
                  the spots from feeder.json, and how big a bird is drawn at
                  each of them, read off depth-map.png
  --overlay       the scene at 320x240 x3 with the feeder pasted and every spot
                  marked, for checking the coordinates by eye

Bird sprites are baked separately: sheet_cut.py --bake.

Depth: depth-map.png is a relative depth estimate of the photo (brighter is
nearer). A bird's size goes with how near its spot is against the feeder's
plane, the sprites being sized for the feeder: t = (d - far) / (feeder - far),
with far the 5th percentile of the map (the spruces and the fence) and feeder the
median over the feeder. Such maps squash the far range, and at t the blackbird
on the ground still looked as if it stood right behind the feeder, so the size
is t ** DEPTH_GAMMA.
"""

import argparse
import io
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = Path(__file__).resolve().parent
MAIN = HERE.parent / "main" / "scene"
BACKGROUNDS = [("bg_winter_overcast_empty.png", "BG_WINTER_OVERCAST"),
               ("bg_winter_morning_empty.png", "BG_WINTER_MORNING"),
               ("bg_autumn_empty.png", "BG_AUTUMN")]
KINDS = ["perch", "tray", "side", "branch", "trunk", "ground"]
DEPTH_GAMMA = 1.5
SCALE_MIN, SCALE_MAX = 0.15, 1.0
BRANCH_NEAR = 0.8     # depth, 0 far .. 1 the feeder: nearer than this is the branch
BRANCH_MAX_Y = 0.72   # share of the picture height; below it is ground, however near


def c_bytes(data):
    return "\n".join("  " + ",".join(f"0x{b:02x}" for b in data[k:k + 16]) + "," for k in range(0, len(data), 16))


def bake_backgrounds(assets, W, H):
    out = ["// Generated by tools/make_assets.py - do not edit.",
           "// The feeder scene's backgrounds without the feeder, 320x240 JPEG.", '#include "feeder_bg.h"', ""]
    for i, (name, _) in enumerate(BACKGROUNDS):
        img = Image.open(assets / name).convert("RGB").resize((W, H), Image.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, "JPEG", quality=90)
        jpg = buf.getvalue()
        print(f"{name}: {len(jpg)} bytes")
        out += [f"// {name}", f"static const uint8_t bg{i}[] PROGMEM = {{", c_bytes(jpg), "};", ""]
    out.append("const FeederBg FEEDER_BG[N_FEEDER_BG] = {")
    out += [f"  {{ bg{i}, sizeof(bg{i}) }},   // {name}" for i, (name, _) in enumerate(BACKGROUNDS)]
    out.append("};")
    (MAIN / "feeder_bg.cpp").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    h = ["#ifndef FEEDER_BG_H", "#define FEEDER_BG_H",
         "// Generated by tools/make_assets.py - do not edit.", "#include <Arduino.h>", "",
         "struct FeederBg { const uint8_t* data; uint32_t len; };", "",
         f"static const int N_FEEDER_BG = {len(BACKGROUNDS)};"]
    h += [f"static const int {sym} = {i};" for i, (_, sym) in enumerate(BACKGROUNDS)]
    h += ["extern const FeederBg FEEDER_BG[N_FEEDER_BG];", "", "#endif", ""]
    (MAIN / "feeder_bg.h").write_text("\n".join(h), encoding="utf-8", newline="\n")


def premul_box(rgba, size):
    a = rgba.astype(float)
    al = a[..., 3:4] / 255.0
    pm = Image.fromarray(np.dstack([a[..., :3] * al, a[..., 3:4]]).astype(np.uint8), "RGBA")
    small = np.asarray(pm.resize(size, Image.BOX), dtype=float)
    sal = small[..., 3:4] / 255.0
    col = np.where(sal > 0.004, small[..., :3] / np.maximum(sal, 0.004), 0)
    return np.dstack([np.clip(col, 0, 255), small[..., 3:4]]).astype(np.uint8)


class Depth:
    def __init__(self, assets, SW, SH, feeder_alpha):
        d = Image.open(assets / "depth-map.png").convert("L").resize((SW, SH), Image.BILINEAR)
        self.d = np.asarray(d, dtype=float)
        self.far = float(np.percentile(self.d, 5))
        self.feeder = float(np.median(self.d[feeder_alpha > 128]))
        print(f"depth: far {self.far:.0f}, feeder {self.feeder:.0f}")

    def scale(self, v):
        t = (v - self.far) / (self.feeder - self.far)
        t = min(max(t, 0.0), 1.0)
        return min(max(t ** DEPTH_GAMMA, SCALE_MIN), SCALE_MAX)

    def under(self, x, y, kind):
        # what a bird at (x, y) holds on to: below its feet on a branch; beside
        # it on the trunk, where it clings to the side of the stem. The nearest
        # thing there is that, not the sky or the spruces around it.
        H, W = self.d.shape
        if kind == "trunk":
            patch = self.d[max(0, y - 12):min(H, y + 12), max(0, x - 40):min(W, x + 40)]
        else:
            patch = self.d[max(0, y + 2):min(H, y + 16), max(0, x - 8):min(W, x + 8)]
        return float(patch.max()) if patch.size else self.far


def bake_feeder(assets, spec):
    SW, SH = spec["source_px"]
    W, H = spec["scene_px"]
    k = W / SW
    cut = np.asarray(Image.open(assets / "feeder_cutout.png").convert("RGBA")).copy()
    mask = np.asarray(Image.open(assets / "feeder_mask.png").convert("L")) > 127
    px, py = spec["pivot"]
    cut[..., 3] = np.where(mask, cut[..., 3], 0)
    cut[:py, :, 3] = 0  # below the knot only
    depth = Depth(assets, SW, SH, cut[..., 3])
    ys, xs = np.nonzero(cut[..., 3] > 8)
    x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
    # widen to whole scene pixels so the reduction lines up with the background
    sx0, sy0 = int(np.floor(x0 * k)), int(np.floor(y0 * k))
    sx1, sy1 = int(np.ceil(x1 * k)), int(np.ceil(y1 * k))
    fx0, fy0 = int(round(sx0 / k)), int(round(sy0 / k))
    fx1, fy1 = min(SW, int(round(sx1 / k))), min(SH, int(round(sy1 / k)))
    # the part of the feeder in front of the birds on the tray (feeder.json "front")
    front = Image.new("L", (SW, SH), 0)
    for poly in spec["front"]:
        ImageDraw.Draw(front).polygon([tuple(p) for p in poly], fill=255)
    front_alpha = (cut[..., 3].astype(float) * (np.asarray(front) / 255.0)).astype(np.uint8)
    sprites, fronts = [], []
    for name, _ in BACKGROUNDS:
        photo = np.asarray(Image.open(assets / name.replace("_empty", "")).convert("RGB"))
        rgba = np.dstack([photo, cut[..., 3]])
        sprites.append(premul_box(rgba[fy0:fy1, fx0:fx1], (sx1 - sx0, sy1 - sy0)))
        rgba = np.dstack([photo, front_alpha])
        fronts.append(premul_box(rgba[fy0:fy1, fx0:fx1], (sx1 - sx0, sy1 - sy0)))
    sprite = sprites[0]
    w, h = sprite.shape[1], sprite.shape[0]
    ax, ay = px * k - sx0, py * k - sy0
    print(f"feeder {w}x{h} scene px at {sx0},{sy0}, pivot in sprite {ax:.1f},{ay:.1f}")

    lines = ["// Generated by tools/make_assets.py - do not edit.", '#include "feeder_art.h"', ""]
    for i, (name, _) in enumerate(BACKGROUNDS):
        for label, arr, pics in (("the feeder", "art", sprites), ("its roof and front post", "front", fronts)):
            lines += [f"// {label} from {name.replace('_empty', '')}", f"static const RGBA8 {arr}{i}[{w * h}] PROGMEM = {{"]
            for y in range(h):
                lines.append("  " + ", ".join("{%3d,%3d,%3d,%3d}" % tuple(int(v) for v in pics[i][y, x]) for x in range(w)) + ",")
            lines += ["};", ""]
    for arr, sym in (("art", "FEEDER_ARTS"), ("front", "FEEDER_FRONTS")):
        lines += [f"const RGBA8* const {sym}[{len(BACKGROUNDS)}] = {{ " +
                  ", ".join(f"{arr}{i}" for i in range(len(BACKGROUNDS))) + " };"]
    lines.append("")
    lines += ["const FeederSpot FEEDER_SPOTS[N_FEEDER_SPOTS] = {"]
    spots = spec["spots"]
    ground = None
    for s in spots:
        kind = "SPOT_" + s["kind"].upper()
        if "area" in s:
            ground = s["area"]
            ax0, ay0, ax1, ay1 = [v * k for v in s["area"]]
            lines.append(f'  {{ "{s["name"]}", {kind}, false, {ax0:.1f}f, {ay0:.1f}f, {ax1:.1f}f, {ay1:.1f}f, 1.0f }},')
            continue
        # on the feeder the sprites are at their own size; elsewhere the depth map says
        sc = 1.0 if s["on"] == "feeder" else depth.scale(depth.under(s["at"][0], s["at"][1], s["kind"]))
        print(f"  {s['name']:12s} scale {sc:.2f}")
        if s["on"] == "feeder":
            lx, ly = (s["at"][0] - px) * k, (s["at"][1] - py) * k
            lines.append(f'  {{ "{s["name"]}", {kind}, true, {lx:.1f}f, {ly:.1f}f, 0, 0, {sc:.2f}f }},')
        else:
            lines.append(f'  {{ "{s["name"]}", {kind}, false, {s["at"][0] * k:.1f}f, {s["at"][1] * k:.1f}f, 0, 0, {sc:.2f}f }},')
    lines.append("};")
    lines.append("")

    # the ground, row by row: the median depth across the ground area on each row
    gx0, gy0, gx1, gy1 = ground
    rows = []
    for ys in range(H):
        y = int((ys + 0.5) / k)
        y = min(max(y, gy0), gy1)
        rows.append(depth.scale(float(np.median(depth.d[y, gx0:gx1]))))
    print(f"  ground scale {rows[int(gy0 * k)]:.2f} at the back .. {rows[min(H - 1, int(gy1 * k))]:.2f} at the front")
    lines.append(f"const float GROUND_SCALE[{H}] = {{")
    for i in range(0, H, 12):
        lines.append("  " + ", ".join(f"{v:.3f}f" for v in rows[i:i + 12]) + ",")
    lines.append("};")

    # the branch, for the sway (sky.h): what the depth map puts as near as the
    # feeder, above the ground and without the feeder itself (the string and the
    # knot above the pivot stay: they are part of the branch in the photo). The
    # depth map's twigs are a pixel or two off the photos', so the mask is a few
    # pixels wider than the wood and soft: the whole twig moves, and the bend
    # runs out in the blurred garden behind it, where it cannot be seen.
    t = (depth.d - depth.far) / (depth.feeder - depth.far)
    near = t > BRANCH_NEAR
    feeder_zone = np.asarray(Image.fromarray((mask * 255).astype(np.uint8)).filter(ImageFilter.MaxFilter(21))) > 0
    near[py:, :] &= ~feeder_zone[py:, :]
    near[int(BRANCH_MAX_Y * SH):, :] = False
    m = Image.fromarray((near * 255).astype(np.uint8)).resize((W, H), Image.BOX)
    m = m.filter(ImageFilter.MaxFilter(7)).filter(ImageFilter.GaussianBlur(2.0))
    branch = np.clip(np.asarray(m, dtype=float) * 1.6, 0, 255).astype(np.uint8)
    print(f"  branch mask: {int((branch > 0).sum())} scene px")
    lines += ["", "// the branch in the photo, 0..255, row by row (y * 320 + x)",
              f"const uint8_t BRANCH_MASK[{W * H}] PROGMEM = {{"]
    for y in range(H):
        lines.append("  " + ",".join(str(int(v)) for v in branch[y]) + ",")
    lines.append("};")
    # the wood alone, not widened: what hides a leaf or a flake falling behind it
    # (fall.h; without it the falling leaves passed over the branch in front of them)
    wood = Image.fromarray((near * 255).astype(np.uint8)).resize((W, H), Image.BOX)
    wood = np.clip(np.asarray(wood, dtype=float) * 1.4, 0, 255).astype(np.uint8)
    lines += ["", "// the wood of the branch alone, 0..255: it hides what falls behind it",
              f"const uint8_t BRANCH_WOOD[{W * H}] PROGMEM = {{"]
    for y in range(H):
        lines.append("  " + ",".join(str(int(v)) for v in wood[y]) + ",")
    lines.append("};")
    (MAIN / "feeder_art.cpp").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    hdr = ["#ifndef FEEDER_ART_H", "#define FEEDER_ART_H",
           "// Generated by tools/make_assets.py - do not edit.", '#include "fish_art.h"', "",
           "enum SpotKind : uint8_t { " + ", ".join(f"SPOT_{n.upper()}" for n in KINDS) + " };", "",
           "struct FeederSpot {",
           "  const char* name;",
           "  SpotKind    kind;",
           "  bool        onFeeder;  // true: x, y from the pivot, swinging; false: scene pixels",
           "  float       x, y;",
           "  float       x1, y1;    // the far corner, for an area (the ground)",
           "  float       scale;     // how big a bird is drawn here, from the depth map",
           "};", "",
           f"static const int FEEDER_W = {w};",
           f"static const int FEEDER_H = {h};",
           f"static const float FEEDER_PIVOT_X = {px * k:.2f}f;   // scene pixels",
           f"static const float FEEDER_PIVOT_Y = {py * k:.2f}f;",
           f"static const float FEEDER_ANCHOR_X = {ax:.2f}f;  // the pivot inside the sprite",
           f"static const float FEEDER_ANCHOR_Y = {ay:.2f}f;",
           f"static const float PX_PER_CM = {spec['px_per_cm']}f;",
           f"// the feeder as it looks in each background (FEEDER_BG order), {w * h} pixels each",
           f"extern const RGBA8* const FEEDER_ARTS[{len(BACKGROUNDS)}];",
           "// only the roof and the front post: drawn again over the birds on the tray",
           f"extern const RGBA8* const FEEDER_FRONTS[{len(BACKGROUNDS)}];", "",
           f"static const int N_FEEDER_SPOTS = {len(spots)};",
           "extern const FeederSpot FEEDER_SPOTS[N_FEEDER_SPOTS];",
           "// bird size on the ground, per scene row, from the depth map",
           f"extern const float GROUND_SCALE[{H}];",
           "// the branch in the photo, 0..255 per scene pixel (y * 320 + x): where the sway bends it",
           f"extern const uint8_t BRANCH_MASK[{W * H}];",
           "// the wood alone, not widened: it hides the leaves and flakes falling behind it",
           f"extern const uint8_t BRANCH_WOOD[{W * H}];", "", "#endif", ""]
    (MAIN / "feeder_art.h").write_text("\n".join(hdr), encoding="utf-8", newline="\n")
    return sprite, (sx0, sy0), (px * k, py * k)


def overlay(assets, spec, sprite, origin, pivot, path):
    W, H = spec["scene_px"]
    k = W / spec["source_px"][0]
    bg = Image.open(assets / BACKGROUNDS[0][0]).convert("RGBA").resize((W, H), Image.LANCZOS)
    bg.alpha_composite(Image.fromarray(sprite, "RGBA"), origin)
    big = bg.resize((W * 3, H * 3), Image.NEAREST)
    d = ImageDraw.Draw(big)
    colours = {"perch": (255, 60, 60), "tray": (255, 200, 0), "side": (255, 0, 255), "branch": (0, 220, 255),
               "trunk": (0, 255, 120), "ground": (120, 120, 255)}
    for s in spec["spots"]:
        c = colours[s["kind"]]
        if "area" in s:
            x0, y0, x1, y1 = [v * k * 3 for v in s["area"]]
            d.rectangle((x0, y0, x1, y1), outline=c, width=2)
        else:
            x, y = s["at"][0] * k * 3, s["at"][1] * k * 3
            d.ellipse((x - 5, y - 5, x + 5, y + 5), outline=c, width=2)
            d.text((x + 7, y - 7), s["name"], fill=c)
    x, y = pivot[0] * 3, pivot[1] * 3
    d.line((x - 8, y, x + 8, y), fill=(255, 255, 255), width=2)
    d.line((x, y - 8, x, y + 8), fill=(255, 255, 255), width=2)
    big.save(path)
    print(f"overlay {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("assets")
    ap.add_argument("--overlay")
    args = ap.parse_args()
    assets = Path(args.assets)
    spec = json.loads((HERE / "feeder.json").read_text(encoding="utf-8"))
    MAIN.mkdir(parents=True, exist_ok=True)
    W, H = spec["scene_px"]
    bake_backgrounds(assets, W, H)
    sprite, origin, pivot = bake_feeder(assets, spec)
    if args.overlay:
        overlay(assets, spec, sprite, origin, pivot, args.overlay)


if __name__ == "__main__":
    main()
